/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package xianqi_other;

import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Laura Sabillon
 */
public class MENU_PRINCIPAL extends javax.swing.JFrame {
    private Usuarios data;
    private Manejo_usuarios user;
    boolean visibility = false;
    String[] items = {};
    /**
     * Creates new form MENU_PRINCIPAL
     */
    public MENU_PRINCIPAL(Manejo_usuarios user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        cuenta = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        panel_reportes = new javax.swing.JPanel();
        ranking = new javax.swing.JButton();
        logs = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("MENU INICIAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 630, -1));

        logout.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("4.- LOG OUT");
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 300, 60));

        jugar.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jugar.setForeground(new java.awt.Color(255, 255, 255));
        jugar.setText("1.- JUGAR XIANGQI");
        jugar.setContentAreaFilled(false);
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 300, 60));

        cuenta.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        cuenta.setForeground(new java.awt.Color(255, 255, 255));
        cuenta.setText("2.- MI CUENTA");
        cuenta.setContentAreaFilled(false);
        cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaActionPerformed(evt);
            }
        });
        getContentPane().add(cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, 60));

        reportes.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setText("3.- REPORTES");
        reportes.setContentAreaFilled(false);
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        getContentPane().add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 300, 50));

        panel_reportes.setBackground(new java.awt.Color(204, 51, 0));
        panel_reportes.setOpaque(false);
        panel_reportes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_reportesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panel_reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ranking.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        ranking.setForeground(new java.awt.Color(255, 255, 255));
        ranking.setText("a.- Ranking de Jugadores         ");
        ranking.setContentAreaFilled(false);
        ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingActionPerformed(evt);
            }
        });
        panel_reportes.add(ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        logs.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        logs.setForeground(new java.awt.Color(255, 255, 255));
        logs.setText("b.- Logs de mis ultimos juegos");
        logs.setContentAreaFilled(false);
        logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsActionPerformed(evt);
            }
        });
        panel_reportes.add(logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 237, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue_button (9).jpg"))); // NOI18N
        panel_reportes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue_button (9).jpg"))); // NOI18N
        panel_reportes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        getContentPane().add(panel_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 250, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue_button (4).jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue_button (4).jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue_button (4).jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue_button (4).jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20432619.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-860, -390, 2560, 1300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Usuarios data = user.InSession(); 
        if (data != null) {
            data.setActivo(false);
        }        
        LOG_in log = new LOG_in(this.user);
        log.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_logoutActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        // TODO add your handling code here:
        visibility = !visibility; 
        panel_reportes.setVisible(visibility);
    }//GEN-LAST:event_reportesActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        ArrayList < Usuarios > Lista = user.getUsuarios();
        Usuarios currentUser = user.InSession(); 

        if (Lista.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay ningún jugador disponible.", "No hay jugadores", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ArrayList <String> itemsList = new ArrayList<>();

            for (Usuarios usuario : Lista) {
                if (usuario != null && !usuario.equals(currentUser)) {
                    itemsList.add(usuario.getUsuario());
                }
            }

            String[] items = itemsList.toArray(new String[0]);

            if (items.length == 0) {
                JOptionPane.showMessageDialog(null, "No hay otros jugadores disponibles.", "No hay jugadores", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JList < String> jugadores = new JList<>(items);
                JScrollPane scrollPane = new JScrollPane(jugadores);

                int option = JOptionPane.showConfirmDialog(null, scrollPane, "Seleccione un jugador", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

                if (option == JOptionPane.OK_OPTION && jugadores.getSelectedValue() != null) {
                    String jugador2 = jugadores.getSelectedValue();
                    Tablero tab = new Tablero(this.user, jugador2);
                    tab.setVisible(true);
                    this.dispose();
                } else if (option == JOptionPane.OK_OPTION && jugadores.getSelectedValue() == null) {
                    JOptionPane.showMessageDialog(null, "Para poder jugar se requiere escoger otro jugador.");
                }
            }
        }
    }//GEN-LAST:event_jugarActionPerformed

    private void logsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsActionPerformed
        // TODO add your handling code here:
        String username = user.getUsernameInSession();
        String historia = user.Imprimir_Historia();

        JOptionPane.showMessageDialog(null,historia,"Historia de Partidas", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_logsActionPerformed

    private void panel_reportesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_reportesAncestorAdded
        // TODO add your handling code here:
        if (visibility) {
            panel_reportes.setVisible(true);
        } else {
            panel_reportes.setVisible(false);
        }
    }//GEN-LAST:event_panel_reportesAncestorAdded

    private void cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaActionPerformed
        // TODO add your handling code here:
        CUENTA mi = new CUENTA(this.user);
        mi.setVisible(true);
    }//GEN-LAST:event_cuentaActionPerformed

    private void rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingActionPerformed
        // TODO add your handling code here:
        user.Ranking();

        StringBuilder rankingDisplay = new StringBuilder("Ranking de Usuarios:\n\n");

        for (String usuario : user.getRanking()) {
            rankingDisplay.append(usuario).append("\n");
        }

        JOptionPane.showMessageDialog(null, rankingDisplay.toString(), "Ranking de Usuarios", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        Manejo_usuarios user = new Manejo_usuarios();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_PRINCIPAL(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jugar;
    private javax.swing.JButton logout;
    private javax.swing.JButton logs;
    private javax.swing.JPanel panel_reportes;
    private javax.swing.JButton ranking;
    private javax.swing.JButton reportes;
    // End of variables declaration//GEN-END:variables
}
